version: '3.8'
services:
  mongodb:
    container_name: testing_controller_routes_mongodb
    restart: unless-stopped
    env_file: ./.env
    logging:
      driver: none
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:/data/db
  mongodb-test:
    container_name: testing_controller_routes_mongodb-test
    restart: unless-stopped
    env_file: ./.env
    logging:
      driver: none
    image: mongo:5.0.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
  app:
    depends_on:
      - mongodb
      - mongodb-test
    container_name: testing_controller_routes_node-app
    restart: always
    build: .
    env_file: ./.env
    volumes:
      - ./src:/backend-app/src
      - ./package.json:/backend-app/package.json
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - TEST_DB_HOST=mongodb-test
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - SERVER_PORT=$NODE_LOCAL_PORT
      - IS_DOCKER=true
    stdin_open: true
    tty: true
    links:
      - mongodb
volumes:
  db:
  avatars:
